# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='event date')),
                ('pub_date', models.DateTimeField(verbose_name='published date')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='', verbose_name='event image')),
            ],
        ),
    ]
