# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160605_1526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='GuildEvent',
        ),
    ]
