# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160605_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildevent',
            name='short_description',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guildevent',
            name='image',
            field=models.ImageField(upload_to='home/events', verbose_name='event image'),
        ),
    ]
