# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 17:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160618_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 8, 17, 7, 31, 836963, tzinfo=utc), verbose_name='published date'),
        ),
    ]
