# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160612_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='published date')),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='home/events', verbose_name='event image')),
            ],
        ),
    ]
