# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20160709_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guildevent',
            options={'verbose_name': 'ギルドのイベント', 'verbose_name_plural': 'ギルドのイベント'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': '画像', 'verbose_name_plural': '画像'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'ニュ－ス', 'verbose_name_plural': 'ニュ－ス'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'コメント', 'verbose_name_plural': 'コメント'},
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'ギルドのイベント', 'verbose_name_plural': 'ギルドのイベント'},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'verbose_name': 'スレッド', 'verbose_name_plural': 'スレッド'},
        ),
        migrations.AlterModelOptions(
            name='threadimage',
            options={'verbose_name': 'スレッドの画像', 'verbose_name_plural': 'スレッドの画像'},
        ),
        migrations.AlterField(
            model_name='guildevent',
            name='date',
            field=models.DateTimeField(verbose_name='イベントの予定の日付'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='home/events', verbose_name='イベントの画像'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=2000, verbose_name='コメントの内容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='コメントの日付'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='description',
            field=models.TextField(verbose_name='記述'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='pub_date',
            field=models.DateTimeField(verbose_name='出版の日付'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='short_description',
            field=models.CharField(max_length=120, verbose_name='短い記述'),
        ),
    ]
