# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20160612_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='image',
        ),
    ]
