# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20160710_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guildevent',
            options={'verbose_name': 'イベント', 'verbose_name_plural': 'イベント'},
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'コメントの画像', 'verbose_name_plural': 'コメントの画像'},
        ),
        migrations.AlterField(
            model_name='thread',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='home/threads', verbose_name='バナ－の画像(任意)'),
        ),
    ]
