# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20160710_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='banner',
            field=models.ImageField(blank=True, upload_to='home/threads', verbose_name='バナ－の画像(任意)'),
        ),
    ]
