# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20160713_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='banner_original',
        ),
        migrations.AlterField(
            model_name='thread',
            name='banner',
            field=models.ImageField(blank=True, upload_to='home/threads', verbose_name='バナ－の画像(任意)'),
        ),
    ]
