# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_eventsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildevent',
            name='nb_subscriber',
            field=models.IntegerField(default=0, editable=False, verbose_name='登録人の数'),
        ),
    ]
